Derek's RNA Virus Submission
ababaian/VIRUSxDISCVRY pull request #16
Opened 2023-12-04 23:42 UTC by DerekTea

2023-12-12 07:24 UTC, ababaian commented on virus/virTemplate.md
Please do not modify the Template File in the PR, add your virus as a new file named `virus/p_intestivirus`.

2023-12-12 07:24 UTC, ababaian commented on virus/virTemplate.md
> +### {Posasimilis Intestiviridae}
The suffix `viridae` means "Virus Family", so a single virus cannot be a "viridae", change to "Intestivirus" or something along those lines please.

2023-12-12 07:24 UTC, ababaian commented on virus/virTemplate.md
> +![Posasimilis Intestiviridae](https://github.com/DerekTea/VIRUSxDISCVRY/assets/86479477/622afcb1-19f4-4040-abce-f1cd86152e35)
Include this in the PR please with correct file path.

2023-12-12 07:24 UTC, ababaian commented on virus/virTemplate.md
> +[Uploading MGY441 A3 Virus Seq Runs.csv…]()
Remove Uploading pending text.

2023-12-12 07:24 UTC, ababaian commented on virus/virTemplate.md
> +[MGY441 A3 Virus Seq Runs.csv](https://github.com/DerekTea/VIRUSxDISCVRY/files/13552458/MGY441.A3.Virus.Seq.Runs.csv)
Include data file in the `img` path as PR instructions outline.

2023-12-12 07:24 UTC, ababaian commented on virus/virTemplate.md
>  ### Ecology subsection A...
Give this a more informative title fitting to a report, not a "homework assignment"

2023-12-12 07:24 UTC, ababaian commented on virus/virTemplate.md
> +Facts about Posa-like viruses:
Remove fact list please.

2023-12-12 07:24 UTC, ababaian commented on virus/virTemplate.md
>  ### Virus Genome {Q3}
Convert this to `.png` and include it embedded as an image. The figure legend should be written into the markdown file given below the figure.

2023-12-12 07:24 UTC, ababaian commented on virus/virTemplate.md
> +[MGY441 A3 Viral Genome.pdf](https://github.com/DerekTea/VIRUSxDISCVRY/files/13552439/MGY441.A3.Viral.Genome.pdf)
I'd also recommend moving up your Virus Genome map to the top of the Results section. This makes a more natural fit there prior to the ecology.

2023-12-12 07:24 UTC, ababaian commented on virus/virTemplate.md
>  ### Other (bonus) sections
Better section title please.

2023-12-12 07:24 UTC, ababaian commented on virus/virTemplate.md
> +![Phyre2 3D Structure Motifs](https://github.com/DerekTea/VIRUSxDISCVRY/assets/86479477/5ffb69be-11b9-469f-aade-7a391094007b)
Embed images into PR. Please add descriptive figure legend for each of these.

2023-12-15 07:05 UTC, DerekTea commented
Posasimilaris Intestivirus A3 changes

2023-12-15 07:05 UTC, DerekTea reviewed
Posasimilaris Intestivirus changes

2023-12-15 07:29 UTC, DerekTea commented
Hi professor! I didn't have the "img" file in my virus fork despite forking the entire repository for some reason... i created by own folder named img i hope that works. Thanks!

2023-12-15 15:48 UTC, ababaian requested changes

2023-12-15 15:48 UTC, ababaian commented on virus/img/p_intestivirus/Cobalt Phylogenetic Tree.png
please don't use spaces in your file names.

2023-12-15 15:48 UTC, ababaian commented on virus/virTemplate.md
Please don't delete thetempalte file in your PR.

2023-12-15 15:48 UTC, ababaian commented on virus/p_intestivirus
> +[Cover art Intestivirus](virus/img/p_intestivirus/cover_art_intestivirus.jfif)
Image paths should be `(img/p_intesti...)` The file is already in the `virus/` path and so you're telling it to look for the image in `virus/virus/img/` which does not exist.

2023-12-15 15:48 UTC, ababaian commented on virus/p_intestivirus
> +Figure 1. A) Proposed Genomic Architecture of the Posasimilaris Intestivirus. Conserved sequences were identified with Blastp and aligned with the coding amino acid sequence of the virus. Distance re
For all the Figure Legends, add a `>` in front of the line to make it "Quote Text". This will look nicer.

2023-12-16 17:33 UTC, ababaian approved these changes

2023-12-16 17:33 UTC, merged