BLASTp tool
ababaian/VIRUSxDISCVRY pull request #46
Opened 2024-11-30 02:29 UTC by lorda6

2024-12-02 16:24 UTC, ababaian approved these changes

2024-12-02 18:51 UTC, ababaian requested changes
Please see comments to update the PR.

2024-12-02 18:51 UTC, ababaian commented on tools/img/BLASTp/1
> +
This looks like an empty file. Please remove it.

2024-12-02 18:51 UTC, ababaian commented on tools/img/BLASTp/1.png
Please give more informative names to files than `1` `2` etc...

2024-12-02 18:51 UTC, ababaian commented on tools/img/BLASTp/2 (2).png
Likewise, it's a good standard of practice to not include `(` or `)` or whitespace ` ` in filenames as these characters are trickier to write when using command line (linux) interface.

2024-12-02 18:51 UTC, ababaian commented on tools/img/BLASTp/2 (2).png
Avoid any special character except `-` and `_` or `.`.

2024-12-03 01:00 UTC, lorda6 commented
Hey Dr. Babaian, changes are made. Please review.

2025-11-27 15:21 UTC, merged