Foldseek Tutorial (submitted by the deadline) & MGY441 final project submittions (submitted Dec 4th, 6pm)
ababaian/VIRUSxDISCVRY pull request #49
Opened 2024-11-30 04:00 UTC by izumiando

2024-12-04 23:00 UTC, izumiando commented
Sorry this is on the same pull request, please let me know if I should submit this in a different way

2024-12-05 19:35 UTC, ababaian requested changes
Please see review comments to "close" the PR and complete the task.

2024-12-05 19:35 UTC, ababaian commented on .DS_Store
Remove hidden file from repo.

2024-12-05 19:35 UTC, ababaian commented on tools/.DS_Store
Ditto remove file.

2024-12-05 19:35 UTC, ababaian commented on tools/foldseek_tutorial.html
Please don't include an `html` file, the submission for the repo should be entirely in MarkDown.

2024-12-05 19:35 UTC, ababaian commented on tools/foldseek_tutorial.md
> +![](./img/Foldseek/predict_structure.png)
For each image, the `./` is not needed you should link to the images as `img/Foldseek/predict_structure.png`. Also the "Figure Title" or Figure Text here is not provided so make sure there is text incase the image does not load, that a description is still available.

2024-12-05 19:35 UTC, ababaian commented on tools/img/.DS_Store
Remove

2024-12-05 19:35 UTC, ababaian commented on tools/img/Foldseek/.DS_Store
Remove

2024-12-05 19:35 UTC, ababaian commented on virus/.DS_Store
rm

2024-12-05 19:35 UTC, ababaian commented on virus/Anas_Amicus.md
> +written by: [Izumi Ando](https://github.com/yourname *optional link*)
If you're not linking to your github account, delete the link, else add the link.

2024-12-05 19:35 UTC, ababaian commented on virus/Anas_Amicus.md
> +[Optional: Tutorial 2 Generative AI Cover-art](img/<virusname>/cover.png)
pathname is not valid.

2024-12-05 19:35 UTC, ababaian commented on virus/Anas_Amicus.md
> +![**Figure 1. Genomic Characteristics of Anas Amicus**](./img/Anas_Amicus/SRR8189300_genome_vis.png)
As with tool, fix path here and throughout document.

2024-12-11 01:33 UTC, izumiando commented
requested changes made

2024-12-11 03:44 UTC, ababaian approved these changes

2024-12-11 03:44 UTC, merged