Added BlastP_Bootcamp.md and supporting images
ababaian/VIRUSxDISCVRY pull request #50
Opened 2024-11-30 04:09 UTC by blueshorts

I couldn't find a way to do this through my UofT Gitlab CCBR account so I had to use my personal Github account. My name is Jade Juba.

2024-12-05 19:40 UTC, ababaian requested changes
Great PR! Wonderful tutorial too! Please amend the review comments and you're good to go here!

2024-12-05 19:40 UTC, ababaian commented on tools/BLASTp_Bootcamp.md
> +# BlastP Bootcamp
I really like the title, but can you please rename the markdown document to be consistent in formatting with the other tools. `BLASTp.md`

2024-12-05 19:40 UTC, ababaian commented on tools/BLASTp_Bootcamp.md
> +![](img/BlastP_Bootcamp/enter_sequence.jpg)
It's best practice to include a "Figure Title" incase the image does not load, so that backup text is displayed.

2024-12-05 19:40 UTC, ababaian commented on tools/img/BlastP_Bootcamp/enter_sequence.jpg
Ditto for the `img/<tool>` filepath, please use `BLASTp` as the filepath name for consistency.

2024-12-05 19:40 UTC, ababaian commented on tools/img/BlastP_Bootcamp/enter_sequence.jpg
This will apply to all the images, and the tool document paths will have to be updated accordingly.

2024-12-12 23:06 UTC, blueshorts commented
Sorry for all the commits, I was having trouble but I think it worked! The tutorial file should now be called BLASTp.md, the folder in /img/ should have a matching name, and all code calling up images should reflect these changes.

2024-12-13 19:01 UTC, ababaian approved these changes

2024-12-13 19:01 UTC, merged