Submission of Obeliscus Replicandii
ababaian/VIRUSxDISCVRY pull request #54
Opened 2024-12-04 02:25 UTC by prvnzn

2024-12-05 19:29 UTC, ababaian requested changes

2024-12-05 19:29 UTC, ababaian commented on virus/obeliscus_replicandii.md
> +[Cover Image](img/obeliscus_replicandii/cover_image.png)
I think the images for the push are missing. Please add them to the PR

2024-12-05 20:00 UTC, prvnzn commented
I did the changes on GitHub. I wanted to apologise for some wrong pushes.
GitHub is still very new to me and I hope everything is in place by now.
Also, I did exclude the R code in the VIRUSxDISCVRY submission. Let me know
if I should implement it again. The submission on GitLab for the assignment
contains all the code for my small paper.

Kind regards
Enea

Am Do., 5. Dez. 2024 um 14:29 Uhr schrieb Artem Babaian <
***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In virus/obeliscus_replicandii.md
> <https://github.com/ababaian/VIRUSxDISCVRY/pull/54#discussion_r1871967465>
> :
>
> > @@ -0,0 +1,1196 @@
> +# Unveiling the Obelisk Virus and Its Host-Hijacking Secrets (Despite Limited CPU Cycles)
> +
> +written by: [Enea Provenzano](https://github.com/prvnzn)
> +
> +### Obeliscus Replicandii
> +
> +Obeliscus: Derived from the term “obelisk”
> +
> +Replicandii: Stemming from the Latin “replicare”, meaning “to replicate”
> +
> +This species name highlights the novel replication mechanism
> +hypothesised for the virus, particularly its interaction with the
> +Streptococcus sanguinis RNA polymerase.
> +
> +[Cover Image](img/obeliscus_replicandii/cover_image.png)
>
> I think the images for the push are missing. Please add them to the PR
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ababaian/VIRUSxDISCVRY/pull/54#pullrequestreview-2482684272>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BNJUWC245XANZ2XM3C3E2VL2ECSS7AVCNFSM6AAAAABS7CLEMOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOBSGY4DIMRXGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-11 04:13 UTC, ababaian approved these changes

2024-12-11 04:13 UTC, merged