virTemplate.md submission for final project
ababaian/VIRUSxDISCVRY pull request #65
Opened 2024-12-05 02:39 UTC by jheeswyk

2024-12-05 20:59 UTC, ababaian requested changes
Submission looks really cool :) I'm looking forward to diving into it. Please amend the PR to fix the formatting requirements.

2024-12-05 20:59 UTC, ababaian commented on template/img/alignment.PNG
please place all images in a specific folder for your Obelisk and not in the `template` folder but in the `virus` folder. See other submissions from the last year for examples of how filepaths should look like. Amend the paths in the Markdown submission as well so it works.

2024-12-05 20:59 UTC, ababaian commented on template/img/alignment.PNG:Zone.Identifier
remove empty file.

2024-12-05 20:59 UTC, ababaian commented on template/virTemplate.md
Please don't modify the `virTemplate.md` file directly in your PR. Instead copy the file and re-name it to match your submission. See how the files are arranged in other submission.s

2024-12-05 20:59 UTC, ababaian commented on template/virTemplate.md
>  ### Virus Genome {Q3}
Amend out the "Default Titles" from the document. Your descriptive titles are much better throughout.

2024-12-05 20:59 UTC, ababaian commented on template/virTemplate.md
> +![Fig. 1A: ORFs of Clostridiae-associata centralis as determined by ORFfinder, with nucleotide scale bar. Created with R package gggenes based on GitHub PuravG/Computational-Virus-Discovery](img/geno
if the "Figure Legend" is in the title, it won't be displayed, The square-bracket text here is the "title" shown if the image does not load. Instead put the text in italics underneath the figure.

2024-12-05 23:41 UTC, jheeswyk commented
Hi Artem,
I edited my submission file and renamed it to Clostridiae-associata_centralis.md, changed the filepaths for it and my images as requested, and reverted virTemplate.md to the unfilled version. Please let me know if everything looks good!

2024-12-06 16:16 UTC, ababaian approved these changes

2024-12-06 16:16 UTC, ababaian commented on template/.Rhistory
Please remove/delete dotfiles from the repo.

2024-12-06 16:16 UTC, merged