Edited tutorial tool to embed images and added project submission
ababaian/VIRUSxDISCVRY pull request #67
Opened 2024-12-05 21:04 UTC by caitlinoxleyhmb301

2024-12-05 21:08 UTC, ababaian requested changes

2024-12-05 21:08 UTC, ababaian commented on tools/iqtree.md
> +![Alt text](https://github.com/ababaian/VIRUSxDISCVRY/blob/main/tools/img/iqtree/tutorial_q1.png)
Very close! Great job. You can actually simplify this to "point" from the place where this file lives. so change this to 
```
![Make this a better description](img/iqtree/tutorial_q1.png)
```

2024-12-05 21:08 UTC, ababaian commented on virus/img/Obelisk371/temp
please remove temporary files.

2024-12-05 21:26 UTC, ababaian approved these changes

2024-12-05 21:28 UTC, ababaian commented
Looking good, just make sure you keep the main titles for a "paper"

2024-12-06 17:24 UTC, caitlinoxleyhmb301 commented
Ok, I think I made all the necessary changes.

2024-12-07 01:03 UTC, merged